name: DevOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devops-lab-app ./app

      - name: Verify Kubernetes Files
        run: |
          kubectl version --client
          kubectl apply --dry-run=client --validate=false -f k8s/deployment.yml
          kubectl apply --dry-run=client --validate=false -f k8s/service.yml
